[2023-10-01T15:54:14.772+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Load-Green-Taxi-Data-Web-To-GCS-To-BQ.download_to_gcs scheduled__2019-03-02T06:00:00+00:00 [queued]>
[2023-10-01T15:54:14.796+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Load-Green-Taxi-Data-Web-To-GCS-To-BQ.download_to_gcs scheduled__2019-03-02T06:00:00+00:00 [queued]>
[2023-10-01T15:54:14.796+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 3
[2023-10-01T15:54:15.213+0000] {taskinstance.py:1327} INFO - Executing <Task(WebToGCSHKOperator): download_to_gcs> on 2019-03-02 06:00:00+00:00
[2023-10-01T15:54:15.222+0000] {standard_task_runner.py:57} INFO - Started process 754 to run task
[2023-10-01T15:54:15.226+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Load-Green-Taxi-Data-Web-To-GCS-To-BQ', 'download_to_gcs', 'scheduled__2019-03-02T06:00:00+00:00', '--job-id', '574', '--raw', '--subdir', 'DAGS_FOLDER/web_gcs_bq.py', '--cfg-path', '/tmp/tmpec86gv7c']
[2023-10-01T15:54:15.229+0000] {standard_task_runner.py:85} INFO - Job 574: Subtask download_to_gcs
[2023-10-01T15:54:16.321+0000] {task_command.py:410} INFO - Running <TaskInstance: Load-Green-Taxi-Data-Web-To-GCS-To-BQ.download_to_gcs scheduled__2019-03-02T06:00:00+00:00 [running]> on host 772c7a5949f4
[2023-10-01T15:54:17.060+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Load-Green-Taxi-Data-Web-To-GCS-To-BQ' AIRFLOW_CTX_TASK_ID='download_to_gcs' AIRFLOW_CTX_EXECUTION_DATE='2019-03-02T06:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2019-03-02T06:00:00+00:00'
[2023-10-01T15:54:17.062+0000] {crypto.py:83} WARNING - empty cryptography key - values will not be stored encrypted.
[2023-10-01T15:54:17.062+0000] {base.py:73} INFO - Using connection ID 'google_cloud_default' for task execution.
[2023-10-01T15:54:17.062+0000] {Web_To_GCS_Hook.py:67} INFO - Execute downloading of file from https://github.com/DataTalksClub/nyc-tlc-data/releases/download/green/green_tripdata_2019-03.csv.gz to gs://practice18//green_tripdata_2019-03.csv.gz
[2023-10-01T15:54:23.952+0000] {Web_To_GCS_Hook.py:79} INFO - File written to temporary directory: /tmp/tmpgh6iedk6/green_tripdata_2019-03.csv.gz
[2023-10-01T15:54:54.336+0000] {logging_mixin.py:150} INFO -    VendorID lpep_pickup_datetime  ... trip_type congestion_surcharge
0         2  2019-03-01 00:02:21  ...         1                  0.0
1         2  2019-03-01 00:42:31  ...         1                  0.0
2         1  2019-03-01 00:15:53  ...         1                  0.0
3         2  2019-02-28 23:55:58  ...         1                  0.0
4         2  2019-03-01 00:55:58  ...         1                  0.0

[5 rows x 20 columns]
[2023-10-01T15:55:01.663+0000] {Web_To_GCS_Hook.py:90} INFO - Parquet: green_tripdata_2019-03.csv
[2023-10-01T15:55:38.841+0000] {gcs.py:538} INFO - File /tmp/tmpgh6iedk6/green_tripdata_2019-03.csv uploaded to green/green_tripdata_2019-03.csv in practice18 bucket
[2023-10-01T15:55:40.400+0000] {Web_To_GCS_Hook.py:105} INFO - Loaded file from https://github.com/DataTalksClub/nyc-tlc-data/releases/download/green/green_tripdata_2019-03.csv.gz to gs://practice18//green/green_tripdata_2019-03.csv
[2023-10-01T15:55:41.067+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=Load-Green-Taxi-Data-Web-To-GCS-To-BQ, task_id=download_to_gcs, execution_date=20190302T060000, start_date=20231001T155414, end_date=20231001T155541
[2023-10-01T15:55:50.803+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2023-10-01T15:55:52.300+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-10-01T17:03:38.363+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Load-Green-Taxi-Data-Web-To-GCS-To-BQ.download_to_gcs scheduled__2019-03-02T06:00:00+00:00 [queued]>
[2023-10-01T17:03:38.443+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Load-Green-Taxi-Data-Web-To-GCS-To-BQ.download_to_gcs scheduled__2019-03-02T06:00:00+00:00 [queued]>
[2023-10-01T17:03:38.443+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 3
[2023-10-01T17:03:38.663+0000] {taskinstance.py:1327} INFO - Executing <Task(WebToGCSHKOperator): download_to_gcs> on 2019-03-02 06:00:00+00:00
[2023-10-01T17:03:48.522+0000] {standard_task_runner.py:57} INFO - Started process 1829 to run task
[2023-10-01T17:03:48.526+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Load-Green-Taxi-Data-Web-To-GCS-To-BQ', 'download_to_gcs', 'scheduled__2019-03-02T06:00:00+00:00', '--job-id', '584', '--raw', '--subdir', 'DAGS_FOLDER/web_gcs_bq.py', '--cfg-path', '/tmp/tmpo82f1dfq']
[2023-10-01T17:03:48.530+0000] {standard_task_runner.py:85} INFO - Job 584: Subtask download_to_gcs
[2023-10-01T17:03:49.641+0000] {task_command.py:410} INFO - Running <TaskInstance: Load-Green-Taxi-Data-Web-To-GCS-To-BQ.download_to_gcs scheduled__2019-03-02T06:00:00+00:00 [running]> on host 772c7a5949f4
[2023-10-01T17:03:51.366+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Load-Green-Taxi-Data-Web-To-GCS-To-BQ' AIRFLOW_CTX_TASK_ID='download_to_gcs' AIRFLOW_CTX_EXECUTION_DATE='2019-03-02T06:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2019-03-02T06:00:00+00:00'
[2023-10-01T17:03:51.367+0000] {crypto.py:83} WARNING - empty cryptography key - values will not be stored encrypted.
[2023-10-01T17:03:51.367+0000] {base.py:73} INFO - Using connection ID 'google_cloud_default' for task execution.
[2023-10-01T17:03:51.368+0000] {Web_To_GCS_Hook.py:67} INFO - Execute downloading of file from https://github.com/DataTalksClub/nyc-tlc-data/releases/download/green/green_tripdata_2019-03.csv.gz to gs://practice18//green_tripdata_2019-03.csv.gz
[2023-10-01T17:03:51.373+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connection.py", line 175, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/util/connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/local/lib/python3.7/socket.py", line 752, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 721, in urlopen
    chunked=chunked,
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 403, in _make_request
    self._validate_conn(conn)
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 1053, in _validate_conn
    conn.connect()
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connection.py", line 363, in connect
    self.sock = conn = self._new_conn()
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connection.py", line 187, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7fef855112d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/requests/adapters.py", line 497, in send
    chunked=chunked,
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 799, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='github.com', port=443): Max retries exceeded with url: /DataTalksClub/nyc-tlc-data/releases/download/green/green_tripdata_2019-03.csv.gz (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fef855112d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/airflow/plugins/web/operators/Web_To_GCS_Hook.py", line 58, in execute
    self._copy_file_object(gcs_hook)
  File "/opt/airflow/plugins/web/operators/Web_To_GCS_Hook.py", line 75, in _copy_file_object
    r = requests.get(request_url)
  File "/home/airflow/.local/lib/python3.7/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='github.com', port=443): Max retries exceeded with url: /DataTalksClub/nyc-tlc-data/releases/download/green/green_tripdata_2019-03.csv.gz (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fef855112d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
[2023-10-01T17:03:51.384+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=Load-Green-Taxi-Data-Web-To-GCS-To-BQ, task_id=download_to_gcs, execution_date=20190302T060000, start_date=20231001T170338, end_date=20231001T170351
[2023-10-01T17:03:51.597+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 584 for task download_to_gcs (HTTPSConnectionPool(host='github.com', port=443): Max retries exceeded with url: /DataTalksClub/nyc-tlc-data/releases/download/green/green_tripdata_2019-03.csv.gz (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fef855112d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')); 1829)
[2023-10-01T17:03:51.642+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-10-01T17:03:51.699+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-10-01T17:32:23.845+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Load-Green-Taxi-Data-Web-To-GCS-To-BQ.download_to_gcs scheduled__2019-03-02T06:00:00+00:00 [queued]>
[2023-10-01T17:32:23.931+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Load-Green-Taxi-Data-Web-To-GCS-To-BQ.download_to_gcs scheduled__2019-03-02T06:00:00+00:00 [queued]>
[2023-10-01T17:32:23.932+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 3
[2023-10-01T17:32:24.098+0000] {taskinstance.py:1327} INFO - Executing <Task(WebToGCSHKOperator): download_to_gcs> on 2019-03-02 06:00:00+00:00
[2023-10-01T17:32:24.108+0000] {standard_task_runner.py:57} INFO - Started process 2323 to run task
[2023-10-01T17:32:24.112+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Load-Green-Taxi-Data-Web-To-GCS-To-BQ', 'download_to_gcs', 'scheduled__2019-03-02T06:00:00+00:00', '--job-id', '603', '--raw', '--subdir', 'DAGS_FOLDER/web_gcs_bq.py', '--cfg-path', '/tmp/tmp0nkcec8f']
[2023-10-01T17:32:24.115+0000] {standard_task_runner.py:85} INFO - Job 603: Subtask download_to_gcs
[2023-10-01T17:32:24.266+0000] {task_command.py:410} INFO - Running <TaskInstance: Load-Green-Taxi-Data-Web-To-GCS-To-BQ.download_to_gcs scheduled__2019-03-02T06:00:00+00:00 [running]> on host 772c7a5949f4
[2023-10-01T17:32:24.812+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Load-Green-Taxi-Data-Web-To-GCS-To-BQ' AIRFLOW_CTX_TASK_ID='download_to_gcs' AIRFLOW_CTX_EXECUTION_DATE='2019-03-02T06:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2019-03-02T06:00:00+00:00'
[2023-10-01T17:32:24.814+0000] {crypto.py:83} WARNING - empty cryptography key - values will not be stored encrypted.
[2023-10-01T17:32:24.814+0000] {base.py:73} INFO - Using connection ID 'google_cloud_default' for task execution.
[2023-10-01T17:32:24.814+0000] {Web_To_GCS_Hook.py:67} INFO - Execute downloading of file from https://github.com/DataTalksClub/nyc-tlc-data/releases/download/green/green_tripdata_2019-03.csv.gz to gs://practice18//green_tripdata_2019-03.csv.gz
[2023-10-01T17:32:29.331+0000] {Web_To_GCS_Hook.py:79} INFO - File written to temporary directory: /tmp/tmpp_sr4jl9/green_tripdata_2019-03.csv.gz
[2023-10-01T17:32:31.192+0000] {logging_mixin.py:150} INFO -    VendorID lpep_pickup_datetime  ... trip_type congestion_surcharge
0         2  2019-03-01 00:02:21  ...         1                  0.0
1         2  2019-03-01 00:42:31  ...         1                  0.0
2         1  2019-03-01 00:15:53  ...         1                  0.0
3         2  2019-02-28 23:55:58  ...         1                  0.0
4         2  2019-03-01 00:55:58  ...         1                  0.0

[5 rows x 20 columns]
[2023-10-01T17:32:38.079+0000] {Web_To_GCS_Hook.py:90} INFO - Parquet: green_tripdata_2019-03.csv
[2023-10-01T17:33:07.863+0000] {gcs.py:538} INFO - File /tmp/tmpp_sr4jl9/green_tripdata_2019-03.csv uploaded to green/green_tripdata_2019-03.csv in practice18 bucket
[2023-10-01T17:33:07.864+0000] {Web_To_GCS_Hook.py:105} INFO - Loaded file from https://github.com/DataTalksClub/nyc-tlc-data/releases/download/green/green_tripdata_2019-03.csv.gz to gs://practice18//green/green_tripdata_2019-03.csv
[2023-10-01T17:33:07.957+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=Load-Green-Taxi-Data-Web-To-GCS-To-BQ, task_id=download_to_gcs, execution_date=20190302T060000, start_date=20231001T173223, end_date=20231001T173307
[2023-10-01T17:33:08.418+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2023-10-01T17:33:08.698+0000] {taskinstance.py:2653} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2023-10-01T19:51:18.514+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Load-Green-Taxi-Data-Web-To-GCS-To-BQ.download_to_gcs scheduled__2019-03-02T06:00:00+00:00 [queued]>
[2023-10-01T19:51:18.666+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Load-Green-Taxi-Data-Web-To-GCS-To-BQ.download_to_gcs scheduled__2019-03-02T06:00:00+00:00 [queued]>
[2023-10-01T19:51:18.666+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 3
[2023-10-01T19:51:18.772+0000] {taskinstance.py:1327} INFO - Executing <Task(WebToGCSHKOperator): download_to_gcs> on 2019-03-02 06:00:00+00:00
[2023-10-01T19:51:18.790+0000] {standard_task_runner.py:57} INFO - Started process 4594 to run task
[2023-10-01T19:51:18.794+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Load-Green-Taxi-Data-Web-To-GCS-To-BQ', 'download_to_gcs', 'scheduled__2019-03-02T06:00:00+00:00', '--job-id', '631', '--raw', '--subdir', 'DAGS_FOLDER/web_gcs_bq.py', '--cfg-path', '/tmp/tmpqk9zz1me']
[2023-10-01T19:51:18.796+0000] {standard_task_runner.py:85} INFO - Job 631: Subtask download_to_gcs
[2023-10-01T19:51:18.879+0000] {task_command.py:410} INFO - Running <TaskInstance: Load-Green-Taxi-Data-Web-To-GCS-To-BQ.download_to_gcs scheduled__2019-03-02T06:00:00+00:00 [running]> on host 772c7a5949f4
[2023-10-01T19:51:19.116+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Load-Green-Taxi-Data-Web-To-GCS-To-BQ' AIRFLOW_CTX_TASK_ID='download_to_gcs' AIRFLOW_CTX_EXECUTION_DATE='2019-03-02T06:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2019-03-02T06:00:00+00:00'
[2023-10-01T19:51:19.117+0000] {crypto.py:83} WARNING - empty cryptography key - values will not be stored encrypted.
[2023-10-01T19:51:19.118+0000] {base.py:73} INFO - Using connection ID 'google_cloud_default' for task execution.
[2023-10-01T19:51:19.118+0000] {Web_To_GCS_Hook.py:67} INFO - Execute downloading of file from https://github.com/DataTalksClub/nyc-tlc-data/releases/download/green/green_tripdata_2019-03.csv.gz to gs://practice18//green_tripdata_2019-03.csv.gz
[2023-10-01T19:51:20.541+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connection.py", line 175, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/util/connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/local/lib/python3.7/socket.py", line 752, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 721, in urlopen
    chunked=chunked,
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 403, in _make_request
    self._validate_conn(conn)
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 1053, in _validate_conn
    conn.connect()
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connection.py", line 363, in connect
    self.sock = conn = self._new_conn()
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connection.py", line 187, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7fef8551bf50>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/requests/adapters.py", line 497, in send
    chunked=chunked,
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 799, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='github.com', port=443): Max retries exceeded with url: /DataTalksClub/nyc-tlc-data/releases/download/green/green_tripdata_2019-03.csv.gz (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fef8551bf50>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/airflow/plugins/web/operators/Web_To_GCS_Hook.py", line 58, in execute
    self._copy_file_object(gcs_hook)
  File "/opt/airflow/plugins/web/operators/Web_To_GCS_Hook.py", line 75, in _copy_file_object
    r = requests.get(request_url)
  File "/home/airflow/.local/lib/python3.7/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='github.com', port=443): Max retries exceeded with url: /DataTalksClub/nyc-tlc-data/releases/download/green/green_tripdata_2019-03.csv.gz (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fef8551bf50>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
[2023-10-01T19:51:20.755+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=Load-Green-Taxi-Data-Web-To-GCS-To-BQ, task_id=download_to_gcs, execution_date=20190302T060000, start_date=20231001T195118, end_date=20231001T195120
[2023-10-01T19:51:21.081+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 631 for task download_to_gcs (HTTPSConnectionPool(host='github.com', port=443): Max retries exceeded with url: /DataTalksClub/nyc-tlc-data/releases/download/green/green_tripdata_2019-03.csv.gz (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fef8551bf50>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')); 4594)
[2023-10-01T19:51:21.100+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-10-01T19:51:21.130+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
